version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r baemin/requirements.txt
  build:
    commands:
      - python -m unittest discover -s baemin
artifacts:
  files:
    - '**/*'
  base-directory: baemin
