on:
  push:
    branches: 
      - main
      - feature/docker-deploy

name: Deploy to Amazon ECS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: 229008561202
        ECR_REPOSITORY1: themedium-ecr-django
        IMAGE_TAG: ${{ github.sha }}
        ECR_REPOSITORY2: themedium-ecr-nginx
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker-compose build
        docker push 229008561202.dkr.ecr.ap-northeast-2.amazonaws.com/themedium-ecr-nginx:v1.0
        docker push 229008561202.dkr.ecr.ap-northeast-2.amazonaws.com/themedium-ecr-django:v1.0
